= Introduction to networked learning (connectivism)

== Introduction

**Connectivism** is a theory of learning first articulated by George Siemens in 2005 (link:{attachmentsdir}/connectivism-siemens-2005.pdf[pdf]). 

It is included here because:

* as a theory born from the internet age it can play a key role in designing effective online learning experiences
* the idea of school leaders and teachers learning from others, and in turn passing on their expertise, is core to SSAT's purpose

== Overview

Unlike prior theories Connectivism is grounded in the internet age and is framed around the following principles:

* Learning and knowledge rests in diversity of opinions.
* Learning is a process of connecting specialized nodes or information sources.
+
****
These nodes could be individuals - a key part of learning in this theory is based on connections to other people knowledgeable in a field
****
+
* Learning may reside in non-human appliances.
* Capacity to know more is more critical than what is currently known
* Nurturing and maintaining connections is needed to facilitate continual learning.
* Ability to see connections between fields, ideas, and concepts is a core skill.
* Currency (accurate, up-to-date knowledge) is the intent of all connectivist learning
activities.
* Decision-making is itself a learning process. Choosing what to learn and the
meaning of incoming information is seen through the lens of a shifting reality. While
there is a right answer now, it may be wrong tomorrow due to alterations in the
information climate affecting the decision.

== Application

Some of the tools we have at our disposal are well suited to applying a connectivist approach.

xref:e-portfolio.adoc[e-Portfolios] are the perfect tool to support growing learner agency and ability to choose what to learn and how to interpret it. The publishing capabilities in xref:mahara:index.adoc[Mahara] give our learners the ability to be an active part of a knowledge network, giving as well as taking.

xref:discussion-forums.adoc[Discussion forums] are just one opportunity for our learners to exchange perspectives with each other in a safe professional  space.


include::userdoc:ROOT:partial$partial-request-for-material.adoc[] 

