= Overview of e-learning tools available

== Introduction

This page lists the core tools, when specific documentation sections are written links will be added here.

There are many other niche tools that can be used for specific tasks, if there is something you want to use why not https://teams.microsoft.com/l/channel/19%3ada3e76e137e74dab962ca52122e6c1e2%40thread.tacv2/General?groupId=8e1a8b16-7d0e-4704-b2ee-1e290eee7ee9&tenantId=c5263ca1-a2e1-42fd-81bb-effcd1666efd[start a discussion in Teams Digital Delivery/General]?

== Tools Overview

|===

a|*Tool* a|*Applicability to e-Learning* a|*Audience constraints* a|*Other comments*

a|xref:officestaff:msteams:introduction.adoc[Microsoft Teams]
a|* 1:1 messaging / chat
* group messaging / chat
* content sharing
* content co-creation
* live presentations / seminars
a|Best suited to long-running stable groups e.g. 

* Internal (staff) plus anyone with SSAT email address
* Guest users either invited to a meeting or a Team

| Total number of guests in directory limited to 5 x number of Office 365 licences held by company - so we may need to recycle

a|xref:zoom:index.adoc[Zoom]
a|* live presentations / seminars
* content sharing (in context of meeting)

a|Normal licensed limit is 100 attendees per meeting including hosts
|Specific tooling available for integration with Moodle

a|xref:moodle:index.adoc[Moodle]
a|Full LMS functionality including

* courses
* grading
* assignments (individual or group submissions)
* discussion forums (full class or per-group)
* content sharing (from course leader) as files, rich media or web pages
* live chat (whole class or group-based)
* embed Zoom meeting
* integration with Mahara

|Different cohort or group sizes need different management approaches, otherwise only server-size constraints
|Authenticated via SSAT single-sign-on

a|xref:mahara:index.adoc[Mahara]
a|e-Portfolio system offering:

* learner can curate private resource collection including learning logs
* creation of content pages for sharing selected aspects of learner's resources
* learner-controlled sharing of content
* groups with resource-sharing and discussion forums
* integration with Moodle

|Different cohort or group sizes need different management approaches, otherwise only server-size constraints
|Authenticated via SSAT single-sign-on

|===