= Running local development server

== Overview

This page describes how to get a local Moodle devleopment environment up and running on a Windows workstations using WSL2 and Docker.

== Prerequisites

* ensure you have a working linux distribution via WSL2 (recommended is Ubuntu 22.04)
* ensure Docker Desktop is working on your windows machine

== Setup 

* log in to your linux distribution in Windows Terminal +
we assume you use bash as your shell
* clone a copy of the https://bitbucket.org/ssat/moodle.git[SSAT Moodle repository] into a linux directory e.g. ~/moodle. +
We will refer to this directory as `MOODLESOURCEDIR`
* cd into `MOODLESOURCEDIR` and checkout the current integration branch `**{mdl-integration-branch}**`
* `git submodule init`
* `git submodule update --recursive`
* edit ~/.bashrc and set an environment variable that points to the `MOODLESOURCEDIR`
+
```
export MOODLE_DOCKER_WWWROOT=/full/path/to/MOODLESOURCEDIR
```
* also in ~/.bashrc set an enviroment varibale for database type
+
```
export MOODLE_DOCKER_DB=pgsql
```
* `source ~/.bashrc` to set the environment variables
* clone a copy of the   https://github.com/ssatuk/moodle-docker.git[SSAT version of Moodle Docker respository] into another directory e.g. ~/moodledocker +
We will refer to this directory as `MOODLEDOCKERDIR`
* cd into `MOODLEDOCKERDIR`
* `git checkout ssat`
* touch `local.yml`
* edit `local.yml` to add the following content:
+
```
version: "2"
services:
  pgadmin:
    image: dpage/pgadmin4:6.17
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: you@ssatuk.co.uk
      PGADMIN_DEFAULT_PASSWORD:  secret
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "8090:80/tcp"
    volumes:
      - "pgadmin-data:/var/lib/pgadmin"
    
volumes:
  pgadmin-data:
```
* Ensure customized config.php for the Docker containers is in place +
`cp config.docker-template.php $MOODLE_DOCKER_WWWROOT/config.php`

== Operation

=== starting up

* Start the containers +
`bin/moodle-docker-compose up -d`

After a wait for the containers to build, you should be able to access the web front end of Moodle at `http://localhost:8000/` - follow the configuration prompts to set it up.

=== Stopping

In `MOODLEDOCKERDIR` type: +
`bin/moodle-docker-compose stop`

This will stop the containers but leave them configured - next time you run `bin/moodle-docker-compose up` you should start where you left off

=== Destroying the setup

In `MOODLEDOCKERDIR` type: +
`bin/moodle-docker-compose down`

This will stop the containers and destroy them - next time you can start from scratch +
`bin/moodle-docker-compose up -d`

== Editing code

Any changes that you make in `MOODLEDIR` will be reflected in the running containers.

CAUTION: Moodle only supports version increases, you cannot downgrade an existing installation to an earlier version